<?php
/**
 * PayPal Subscriptions
 * @var PayPal\Subscription\Block\Customer\View $block
 * @var PayPal\Subscription\Model\Subscription $subscription
 * @var Escaper $escaper
 */

use Magento\Framework\Escaper;

$subscription = $block->getSubscription();

$frequencyId = $subscription->getFrequencyProfileId();
$releaseDate = $block->formatDate($subscription->getNextReleaseDate());
$shippingPrice = $block->formatPrice($subscription->getShippingPrice());

?>

<section class="block ps-customer-delivery">
    <h3 class="block-title">
        <span><?= $escaper->escapeHtml(__('Delivery & Delivery Methods')) ?></span>
    </h3>
    <div class="block-content">
        <div class="box">
            <h4 class="box-title">
                <span><?= $escaper->escapeHtml(__('Delivery Methods')) ?></span>
            </h4>
            <p><?= $escaper->escapeHtml(__('Your next order will be dispatched on: %1', $releaseDate)) ?></p>
            <div data-bind="scope: 'updateDetails'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
        </div>

        <div class="box">
            <h4 class="box-title">
                <span><?= $escaper->escapeHtml(__('Delivery Methods')) ?></span>
            </h4>
            <div class="box-content">
                <p><?= $escaper->escapeHtml(__('Shipping method: %1', $subscription->getShippingMethod())) ?></p>
                <p><?= $escaper->escapeHtml(__('Shipping price: %1', $shippingPrice), ['span']) ?></p>
            </div>
        </div>
    </div>
</section>

<script type="text/x-magento-init">
    {
        "*": {
             "Magento_Ui/js/core/app": {
                "components": {
                    "updateDetails": {
                        "component": "PayPal_Subscription/js/view/customer/view/delivery",
                        "subscriptionId": <?= $escaper->escapeJs($subscription->getId()); ?>,
                        "options": <?= /* @noEscape */ $block->getFrequencyProfileOptionsJson($frequencyId); ?>,
                        "value": <?= $escaper->escapeJs($subscription->getFrequency()) ?>,
                        "status": <?= $escaper->escapeJs($subscription->getStatus()) ?>
                    }
                }
            }
        }
    }
</script>
