<?php
/**
 * PayPal Subscriptions
 * @var PayPal\Subscription\Block\Customer\History $block
 * @var PayPal\Subscription\Model\SubscriptionHistory $subscriptionHistory
 * @var Escaper $escaper
 */

use Magento\Framework\Escaper;

$subscriptionHistoryCollection = $block->getSubscriptionHistory();
?>
<section class="block ps-customer-history">
    <h3 class="block-title ps-customer-history__title">
        <span><?= $escaper->escapeHtml(__('Past Changes')) ?></span>
    </h3>
    <p><?= $escaper->escapeHtml(__('Past changes to your subscription.')) ?></p>

    <div class="block-content table-wrapper">
        <?php if ($subscriptionHistoryCollection): ?>
            <table class="data table ps-customer-history-table">
                <thead>
                    <tr>
                        <th><?= $escaper->escapeHtml(__('Action')) ?></th>
                        <th><?= $escaper->escapeHtml(__('Description')) ?></th>
                        <th><?= $escaper->escapeHtml(__('Date')) ?></th>
                    </tr>
                </thead>
                <?php foreach ($subscriptionHistoryCollection as $subscriptionHistory): ?>
                    <tr>
                        <td class="col"
                            data-th="<?= $escaper->escapeHtml(__('Action')) ?>">
                            <?= $escaper->escapeHtml($subscriptionHistory->getAction()) ?>
                        </td>
                        <td class="col">
                            <?= $escaper->escapeHtml($subscriptionHistory->getDescription()) ?>
                        </td>
                        <td class="col">
                            <?= $escaper->escapeHtml($block->formatDate($subscriptionHistory->getCreatedAt())) ?>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </table>
            <?php if ($block->getPagerHtml()): ?>
                <div class="toolbar bottom">
                    <?= $block->getPagerHtml() ?>
                </div>
            <?php endif; ?>
        <?php else: ?>
            <p class="message info empty">
                <?= $escaper->escapeHtml(__('No history available.')) ?>
            </p>
        <?php endif; ?>
    </div>
</section>
