<?php
/**
 * PayPal Subscriptions
 * @var PayPal\Subscription\Block\Customer\Payment $block
 * @var Magento\Vault\Api\Data\PaymentTokenInterface $paymentMethod
 * @var Escaper $escaper
 */

use Magento\Framework\Escaper;

$paymentMethods = $block->getPaymentMethods();
?>

<section class="block">
    <h3 class="block-title">
        <strong><?= $escaper->escapeHtml(__('Available payment methods')) ?></strong>
    </h3>
    <div class="block-content">
        <?php if ($paymentMethods): ?>
            <div data-bind="scope: 'selectExistingMethod'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
        <?php else: ?>
            <p class="message info empty">
                <?= $escaper->escapeHtml(__('No payment methods available.')) ?>
            </p>
        <?php endif; ?>
    </div>
</section>

<section class="block">
    <h3 class="block-title">
        <strong><?= $escaper->escapeHtml(__('Add new payment methods')) ?></strong>
    </h3>
    <div class="block-content">
        <div class="box">
            <?= $block->getChildHtml('paypal-subscription-braintree-cc'); ?>
        </div>
        <div class="box">
            <?= $block->getChildHtml('paypal-subscription-braintree-paypal'); ?>
        </div>
    </div>
</section>

<div class="secondary">
    <a class="action" href="<?= $escaper->escapeUrl($block->getBackUrl()) ?>">
        <span><?= $escaper->escapeHtml(__('Back')) ?></span>
    </a>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                  "selectExistingMethod": {
                        "component": "PayPal_Subscription/js/view/customer/payment/select-existing-method",
                        "template": "PayPal_Subscription/customer/payment/select-existing-method",
                        "methods": <?=  /* @noEscape */ $block->getPaymentMethodsJson() ?>,
                        "subscriptionId": "<?= $escaper->escapeHtml($block->getSubscriptionId()) ?>"
                    }
                }
            }
        }
    }
</script>
