<?php
/**
 * PayPal Subscriptions
 * @var PayPal\Subscription\Block\Customer\Payment $block
 * @var Magento\Vault\Api\Data\PaymentTokenInterface $paymentMethod
 * @var Escaper $escaper
 */

use Magento\Framework\Escaper;

$clientTokenUrl = $block->getClientToken();
$updatePaymentUrlPayPal = $block->getUpdatePaymentUrl();

?>

<div data-bind="scope: 'addBraintreePayPal'">
    <h4 class="box-title">
        <span><?= $escaper->escapeHtml(__('Add a new PayPal account')) ?></span>
    </h4>

    <!-- ko if: message -->
        <span class="message error empty" data-bind="i18n: message"></span>
    <!-- /ko -->

    <form class="form"
          data-bind="attr: {action: updatePaymentUrl}"
          method="post"
          novalidate="novalidate">
        <div id="paypal_container"></div>
    </form>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "addBraintreePayPal": {
                        "component": "PayPal_Subscription/js/view/customer/payment/add-braintree-paypal",
                        "clientTokenUrl" : "<?= $escaper->escapeUrl($clientTokenUrl) ?>",
                        "subscriptionId": "<?= $escaper->escapeHtml($block->getSubscriptionId()) ?>",
                        "updatePaymentUrl" : "<?= $escaper->escapeUrl($updatePaymentUrlPayPal) ?>",
                        "disabledFunding" : "",
                        "environment" : "<?= $escaper->escapeHtml($block->getEnvironment()) ?>"
                    }
                }
            }
        }
    }
</script>
