<?php
/**
 * @var \PayPal\Subscription\Block\Adminhtml\Subscriptions\Edit\ShippingMethods $block
 * @var \Magento\Framework\Escaper $escaper
 */
// @codingStandardsIgnoreFile

$subscriptionId = $block->getSubscriptionId();
$shippingRates = $block->getShipping((int) $subscriptionId);
?>
<div class="admin__field-label" data-bind="visible: $data.labelVisible">
    <!-- ko if: $data.label -->
    <label data-bind="attr: {for: uid}">
        <span data-bind="attr: {'data-config-scope': $data.scopeLabel}, i18n: label">Shipping Method</span>
    </label>
    <!-- /ko -->
</div>

<div class="admin__field-control"
     data-bind="
        css: {
            '_with-tooltip': $data.tooltip,
            '_with-reset': $data.showFallbackReset &amp;&amp; $data.isDifferedFromDefault
        }
     ">
<?php foreach ($shippingRates as $rate): ?>
    <?php
    $shippingMethodLabel = sprintf(
        '%s - %s %s',
        $rate->getCarrierTitle(),
        $rate->getMethodTitle(),
        $block->formatPrice($rate->getPrice())
    );
    ?>

    <input id="<?= $escaper->escapeHtmlAttr($rate->getCode()) ?>"
           name="shipping_method"
           type="radio"
           value="<?= $escaper->escapeHtmlAttr($rate->getCode()) ?>"/>

    <label for="<?= $escaper->escapeHtmlAttr($rate->getCode()) ?>">
        <?= $escaper->escapeHtml($shippingMethodLabel, ['span']) ?>
    </label>
    <br/>
<?php endforeach; ?>
</div>
