<?php
/**
 * PayPal Subscriptions
 * Template based off Magento_Customer/templates/address/edit
 *
 * @var Magento\Customer\Block\Address\Edit $block
 * @var PayPal\Subscription\ViewModel\Customer\Address $addressHelper
 */

$addressHelper = $block->getAddressHelper();

$company = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Company::class);
$telephone = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Telephone::class);
$fax = $block->getLayout()->createBlock(\Magento\Customer\Block\Widget\Fax::class);

$streetLines = $addressHelper->getCustomerAddress()->getStreetLines();
$streetValidationClass = $addressHelper->getValidationClass('street');
$streetValidationClass = trim(str_replace('required-entry', '', $streetValidationClass));

$displayAll = $block->getConfig('general/region/display_all');

?>

<div class="block" data-bind="scope: 'addAddress'">
    <h3 class="block-title">
        <span><?= $block->escapeHtml(__('Add New Address')) ?></span>
    </h3>

    <div class="block-content">
        <button class="action primary"
                data-bind="click: openAddressForm">
            <span><?= $block->escapeHtml(__('Add a new address')) ?></span>
        </button>

        <div data-edit-address-modal
             class="ps-add-address-form__container">

             <?= $block->getChildHtml('paypal_subscription_new_address_form', false) ?>
        </div>

    </div>
</div>

<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "addAddress": {
                        "component": "PayPal_Subscription/js/view/customer/addresses/new-address",
                        "subscriptionId": <?= $block->escapeJs($addressHelper->getSubscriptionId()); ?>,
                        "postcodes": <?= /* @noEscape */ $block->getPostCodeConfig()->getSerializedPostCodes(); ?>
                    }
                }
            }
        }
    }
</script>
